<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository
{
    public function findAll() {

        return $this->getEntityManager()
                    ->createQuery('
                            SELECT a, at
                            FROM AppBundle:Activity a
                            LEFT JOIN a.attributes at
                            ORDER BY a.executedAt DESC
                  ')->getResult();
    }
}
