<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository
{
    public function findByDate($date) {

        $dateFrom = clone $date;
        $dateFrom->modify("+1 day");

        return $this->getEntityManager()
                    ->createQuery('
                            SELECT a, at
                            FROM AppBundle:Activity a
                            LEFT JOIN a.attributes at
                            WHERE a.executedAt >= :date_from AND a.executedAt < :date_to
                            ORDER BY a.executedAt DESC
                  ')
                   ->setParameter('date_from', $date)
                   ->setParameter('date_to', $dateFrom)
                   ->getResult();
    }
}
